// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EjercicioExamen;

/************************************************************/
/**
 * 
 */
public class Alimentos {
	/**
	 * 
	 */
	public String Nombre;
	/**
	 * 
	 */
	public float Precio;
	/**
	 * 
	 */
	public Pedidos[] pedidos;

	/**
	 * 
	 */
	public void TipoAlimento() {
	}
}
