// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EjercicioExamen;

/************************************************************/
/**
 * 
 */
public class Camareros extends Empleados {
	/**
	 * 
	 */
	public Alimentos[] alimentos;
}
