// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EjercicioExamen;

/************************************************************/
/**
 * 
 */
public class Clientes extends Restaurante {
}
