// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EjercicioExamen;

/************************************************************/
/**
 * 
 */
public class Empleados extends Restaurante {
	/**
	 * 
	 */
	public long Fecha_Contratacion;
	/**
	 * 
	 */
	public float Salario;
}
