// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EjercicioExamen;

/************************************************************/
/**
 * 
 */
public class Gerentes extends Empleados {
	/**
	 * 
	 */
	public void Estado_Empleados() {
	}

	/**
	 * 
	 */
	public void Modo_Supervisor() {
	}
}
