// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EjercicioExamen;

/************************************************************/
/**
 * 
 */
public class Pedidos {
	/**
	 * 
	 */
	public long Fecha;
	/**
	 * 
	 */
	public long Hora;
	/**
	 * 
	 */
	public float Precio_Total;
	/**
	 * 
	 */
	public Clientes[] clientes;

	/**
	 * 
	 */
	public void InfoAlimentos() {
	}

	/**
	 * 
	 */
	public void CamareroAtendido() {
	}
}
