// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package EjercicioExamen;

/************************************************************/
/**
 * 
 */
public class Restaurante {
	/**
	 * 
	 */
	public String DNI;
	/**
	 * 
	 */
	public String Nombre;
	/**
	 * 
	 */
	public int Telefono;
	/**
	 * 
	 */
	public String Usuario;
	/**
	 * 
	 */
	public String Contraseña;
}
